### PR TITLE
[TSK-227] Repository initiated

### LINKED ISSUE #1: [TSK-227] Initialize the webcam scraper repository
Follow examples for twitter, telegram scrapers and initialize the repository structure for webcam scraper

### PR DESCRIPTION
**Pull request by Rahul-7131**

### CODE REVIEW

**Comment by maany** [comment]
@Rahul-7131 is this ready for merging or you plan to do some more stuff?

**Comment by Rahul-7131** [comment]
@maany this is ready for merging

**Comment by alebg** [comment]
Hi @Rahul-7131 ! I'm taking a look at this scraper. First small remark, are you using the following libraries? I cannot find any imports in the code itself:

- torch (pytorch) (~1GB)
- nvidia_cublas (>300MB)
- All of nvidia_cuda in general, also weights like 1GB

Asking because they are in `requirements.txt` and are very heavy, so the setup of this project is slow. If you're not using them, I'll just remove them from the requirements file

**Comment by Rahul-7131** [comment]
Yeah @alebg ,please do remove them, I was testing them for an image recognition model which I have shifted to climate augmentation repo. They aren't necessary for this scraper here.

**Comment by alebg** [comment]
@Rahul-7131 I cleaned up the setup a bit. Great job! Everything works. Will be working on some fixes to integrate it with the new websat page, but in a different branch. For now I'll just merge this.

**Pull request merged**
